In [ ]:
import sqlite3

try:
    conn = sqlite3.connect('UEFA_ChampionsLeague_db_project_27-12.db')
    cursor = conn.cursor()

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Sponsors(
            Sponsor_ID TEXT PRIMARY KEY,
            Sponsor_Name TEXT,
            Industry TEXT,
            Budget REAL
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Coaches(
            Coach_ID TEXT PRIMARY KEY,
            Coach_Full_Name TEXT,
            First_Name TEXT,
            Last_Name TEXT,
            Nationality TEXT,
            DOB TEXT,
            Team_Name TEXT
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Stadiums(
            Stadium_ID TEXT PRIMARY KEY,
            Stadium_Name TEXT,
            Location TEXT,
            City TEXT,
            Country TEXT,
            Capacity INTEGER,
            Year_Built INTEGER,
            Team_ID TEXT,
            FOREIGN KEY (Team_ID) REFERENCES Teams(Team_ID)
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Teams(
            Team_ID TEXT PRIMARY KEY,
            Team_Name TEXT,
            Main_Owner TEXT,
            Budget REAL,
            Trophy_numbers INTEGER,
            Coach_ID TEXT,
            Sponsor_ID TEXT,
            Foundation_Year INTEGER,
            FOREIGN KEY (Coach_ID) REFERENCES Coaches(Coach_ID) ON DELETE SET NULL,
            FOREIGN KEY (Sponsor_ID) REFERENCES Sponsors(Sponsor_ID) ON DELETE SET NULL
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Players(
            Player_ID TEXT PRIMARY KEY,
            Player_Name TEXT,
            Nationality TEXT,
            DOB TEXT,
            Team_Name TEXT,
            Team_ID TEXT,
            Jersey_Number INTEGER,
            Game_Position TEXT,
            Height REAL,
            Weight REAL,
            Foot TEXT,
            Salary REAL,
            Goals INTEGER,
            Assists INTEGER,
            Transfer_Year INTEGER,
            FOREIGN KEY (Team_ID) REFERENCES Teams(Team_ID) ON DELETE SET NULL
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Tournaments(
            Tournament_ID TEXT PRIMARY KEY,
            Tournament_Name TEXT,
            Year INTEGER,
            Winner TEXT,
            Location TEXT,
            Number_of_Teams INTEGER,
            Sponsor_ID TEXT,
            FOREIGN KEY (Sponsor_ID) REFERENCES Sponsors(Sponsor_ID) ON DELETE SET NULL
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Matches(
            Match_ID TEXT PRIMARY KEY,
            Season TEXT,
            Date_Time TEXT,
            Home_Team_Name TEXT,
            Away_Team_Name TEXT,
            Home_Team_Score INTEGER,
            Away_Team_Score INTEGER,
            Penalty_Shoot_Out INTEGER,
            Attendance INTEGER,
            Duration INTEGER,
            Home_Goals INTEGER,
            Away_Goals INTEGER,
            Yellow_Cards INTEGER,
            Red_Cards INTEGER,
            Home_Team_ID TEXT,
            Away_Team_ID TEXT,
            Stadium_ID TEXT,
            Tournament_ID TEXT,
            Referee_ID TEXT,
            FOREIGN KEY (Home_Team_ID) REFERENCES Teams(Team_ID) ON DELETE SET NULL,
            FOREIGN KEY (Away_Team_ID) REFERENCES Teams(Team_ID) ON DELETE SET NULL,
            FOREIGN KEY (Stadium_ID) REFERENCES Stadiums(Stadium_ID) ON DELETE SET NULL,
            FOREIGN KEY (Tournament_ID) REFERENCES Tournaments(Tournament_ID) ON DELETE SET NULL,
            FOREIGN KEY (Referee_ID) REFERENCES Referees(Referee_ID) ON DELETE SET NULL
        )
    ''')
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Referees(
            Referee_ID TEXT PRIMARY KEY,
            Referee_Name TEXT,
            Nationality TEXT,
            Experience_Years INTEGER,
            Matches_numbers INTEGER,
            Yellow_Cards INTEGER,
            Red_Cards INTEGER
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Goals(
            Goal_ID TEXT PRIMARY KEY,
            Goal_Desc TEXT,
            Scored_ID TEXT,
            Match_Time INTEGER,
            Assist_ID TEXT,
            Match_ID TEXT,
            FOREIGN KEY (Match_ID) REFERENCES Matches(Match_ID) ON DELETE SET NULL
        )
    ''')

    conn.commit()
    conn.close()

except sqlite3.OperationalError as e:
    print("OperationalError:", e)
except Exception as e:
    print("Error:", e)

In [ ]:
import sqlite3
import pandas as pd

# Укажите путь к вашему файлу Excel
excel_file = 'UEFA Champions League 2016-2022 Data_27-12_final.xlsx'

# Подключение к базе данных SQLite
conn = sqlite3.connect('UEFA_ChampionsLeague_db_project_2024.db')
cursor = conn.cursor()

# Список таблиц и листов для импорта
tables_sheets = {
    'Teams': 'Teams',                 # Лист "Teams" в Excel -> Таблица "Teams" в SQLite
    'Players': 'Players',             # Лист "Players" -> Таблица "Players"
    'Matches': 'Matches',             # Лист "Matches" -> Таблица "Matches"
    'Tournaments': 'Tournaments',     # Лист "Tournaments" -> Таблица "Tournaments"
    'Stadiums': 'Stadiums',           # Лист "Stadiums" -> Таблица "Stadiums"
    'Sponsors': 'Sponsors',           # Лист "Sponsors" -> Таблица "Sponsors"
    'Coaches': 'Coaches',             # Лист "Coaches" -> Таблица "Coaches"
    'Referees': 'Referees',           # Лист "Referees" -> Таблица "Referees"
    'Goals': 'Goals'                  # Лист "Goals" -> Таблица "Goals"
}

# Обработка данных из Excel
for table, sheet in tables_sheets.items():
    print(f"Импорт данных для таблицы {table} из листа {sheet}...")

    # Загрузка данных с листа Excel в DataFrame
    df = pd.read_excel(excel_file, sheet_name=sheet)

    # Преобразование данных: например, можно обработать типы данных, если нужно
    # Например, для столбцов с датами:
    # df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

    # Проверка соответствия столбцов (если нужно, можно переименовать столбцы)
    df.rename(columns={"old_column_name": "new_column_name"}, inplace=True)

    # Запись данных DataFrame в SQLite-таблицу
    try:
        # Если таблица существует, добавляем новые записи
        df.to_sql(table, conn, if_exists='append', index=False)
        print(f"Таблица {table} успешно импортирована")
    except Exception as e:
        print(f"Ошибка при импорте данных в таблицу {table}: {e}")

# Закрытие соединения с базой данных
conn.close()

Импорт данных для таблицы Teams из листа Teams...
Таблица Teams успешно импортирована
Импорт данных для таблицы Players из листа Players...
Таблица Players успешно импортирована
Импорт данных для таблицы Matches из листа Matches...
Таблица Matches успешно импортирована
Импорт данных для таблицы Tournaments из листа Tournaments...
Таблица Tournaments успешно импортирована
Импорт данных для таблицы Stadiums из листа Stadiums...
Таблица Stadiums успешно импортирована
Импорт данных для таблицы Sponsors из листа Sponsors...
Таблица Sponsors успешно импортирована
Импорт данных для таблицы Coaches из листа Coaches...
Таблица Coaches успешно импортирована
Импорт данных для таблицы Referees из листа Referees...
Таблица Referees успешно импортирована
Импорт данных для таблицы Goals из листа Goals...
Таблица Goals успешно импортирована

In [ ]:
import sqlite3

try:
    conn = sqlite3.connect('UEFA_ChampionsLeague_db_project_27-12.db')
    cursor = conn.cursor()

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Sponsors(
            Sponsor_ID TEXT PRIMARY KEY,
            Sponsor_Name TEXT,
            Industry TEXT,
            Budget REAL
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Coaches(
            Coach_ID TEXT PRIMARY KEY,
            Coach_Full_Name TEXT,
            First_Name TEXT,
            Last_Name TEXT,
            Nationality TEXT,
            DOB TEXT,
            Team_Name TEXT
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Teams(
            Team_ID TEXT PRIMARY KEY,
            Team_Name TEXT,
            Main_Owner TEXT,
            Budget REAL,
            Trophy_numbers INTEGER,
            Coach_ID TEXT,
            Sponsor_ID TEXT,
            Foundation_Year INTEGER,
            FOREIGN KEY (Coach_ID) REFERENCES Coaches(Coach_ID) ON DELETE SET NULL,
            FOREIGN KEY (Sponsor_ID) REFERENCES Sponsors(Sponsor_ID) ON DELETE SET NULL
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Stadiums(
            Stadium_ID TEXT PRIMARY KEY,
            Stadium_Name TEXT,
            Location TEXT,
            City TEXT,
            Country TEXT,
            Capacity INTEGER,
            Year_Built INTEGER,
            Team_ID TEXT,
            FOREIGN KEY (Team_ID) REFERENCES Teams(Team_ID)
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Players(
            Player_ID TEXT PRIMARY KEY,
            Player_Name TEXT,
            Nationality TEXT,
            DOB TEXT,
            Team_Name TEXT,
            Team_ID TEXT,
            Jersey_Number INTEGER,
            Game_Position TEXT,
            Height REAL,
            Weight REAL,
            Foot TEXT,
            Salary REAL,
            Goals INTEGER,
            Assists INTEGER,
            Transfer_Year INTEGER,
            FOREIGN KEY (Team_ID) REFERENCES Teams(Team_ID) ON DELETE SET NULL
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Tournaments(
            Tournament_ID TEXT PRIMARY KEY,
            Tournament_Name TEXT,
            Year INTEGER,
            Winner TEXT,
            Location TEXT,
            Number_of_Teams INTEGER,
            Sponsor_ID TEXT,
            FOREIGN KEY (Sponsor_ID) REFERENCES Sponsors(Sponsor_ID) ON DELETE SET NULL
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Referees(
            Referee_ID TEXT PRIMARY KEY,
            Referee_Name TEXT,
            Nationality TEXT,
            Experience_Years INTEGER
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Matches(
            Match_ID TEXT PRIMARY KEY,
            Season TEXT,
            Date_Time TEXT,
            Home_Team_Name TEXT,
            Away_Team_Name TEXT,
            Home_Team_Score INTEGER,
            Away_Team_Score INTEGER,
            Penalty_Shoot_Out INTEGER,
            Attendance INTEGER,
            Duration INTEGER,
            Home_Goals INTEGER,
            Away_Goals INTEGER,
            Yellow_Cards INTEGER,
            Red_Cards INTEGER,
            Home_Team_ID TEXT,
            Away_Team_ID TEXT,
            Stadium_ID TEXT,
            Tournament_ID TEXT,
            Referee_ID TEXT,
            FOREIGN KEY (Home_Team_ID) REFERENCES Teams(Team_ID) ON DELETE SET NULL,
            FOREIGN KEY (Away_Team_ID) REFERENCES Teams(Team_ID) ON DELETE SET NULL,
            FOREIGN KEY (Stadium_ID) REFERENCES Stadiums(Stadium_ID) ON DELETE SET NULL,
            FOREIGN KEY (Tournament_ID) REFERENCES Tournaments(Tournament_ID) ON DELETE SET NULL,
            FOREIGN KEY (Referee_ID) REFERENCES Referees(Referee_ID) ON DELETE SET NULL
        )
    ''')

    conn.commit()

except sqlite3.Error as e:
    print(f"An error occurred: {e}")
finally:
    if conn:
        conn.close()